project_id = "gsvvjlgxkmxyhesbpefv"

[functions.send-notification]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.smart-notifications]
verify_jwt = true

[functions.ai-insights]
verify_jwt = true

[functions.face-recognition]
verify_jwt = true

[functions.auto-attendance-notifications]
verify_jwt = false

[functions.face-detection]
verify_jwt = true

[functions.extract-pdf-users]
verify_jwt = true
